apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: ecom
            - name: POSTGRES_INITDB_ARGS
              value: --locale-provider=icu --icu-locale=en-US
            - name: POSTGRES_PASSWORD
              value: E04xSRuM5msjYs1yUMjtOMhwmlk0UG
            - name: POSTGRES_USER
              value: ecom
          image: postgres:16.3-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U ecom -d ecom
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 3
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
